'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:4.0.30319.42000
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings 自動保存機能"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property dayTotalBuy() As Long
            Get
                Return CType(Me("dayTotalBuy"),Long)
            End Get
            Set
                Me("dayTotalBuy") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property dayTotalPay() As Long
            Get
                Return CType(Me("dayTotalPay"),Long)
            End Get
            Set
                Me("dayTotalPay") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property dayTotalParse() As Long
            Get
                Return CType(Me("dayTotalParse"),Long)
            End Get
            Set
                Me("dayTotalParse") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property dayTotalBalance() As Long
            Get
                Return CType(Me("dayTotalBalance"),Long)
            End Get
            Set
                Me("dayTotalBalance") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property remainingFunds() As Long
            Get
                Return CType(Me("remainingFunds"),Long)
            End Get
            Set
                Me("remainingFunds") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property tansyoMode() As Boolean
            Get
                Return CType(Me("tansyoMode"),Boolean)
            End Get
            Set
                Me("tansyoMode") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property tansyoCbV() As Boolean
            Get
                Return CType(Me("tansyoCbV"),Boolean)
            End Get
            Set
                Me("tansyoCbV") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property tansyoExpectLowV() As Double
            Get
                Return CType(Me("tansyoExpectLowV"),Double)
            End Get
            Set
                Me("tansyoExpectLowV") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property tansyoExpectHighV() As Double
            Get
                Return CType(Me("tansyoExpectHighV"),Double)
            End Get
            Set
                Me("tansyoExpectHighV") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property tansyoOddsLowV() As Double
            Get
                Return CType(Me("tansyoOddsLowV"),Double)
            End Get
            Set
                Me("tansyoOddsLowV") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property tansyoOddsHighV() As Double
            Get
                Return CType(Me("tansyoOddsHighV"),Double)
            End Get
            Set
                Me("tansyoOddsHighV") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property tansyoParseV() As Double
            Get
                Return CType(Me("tansyoParseV"),Double)
            End Get
            Set
                Me("tansyoParseV") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property fukusyoCbV() As Boolean
            Get
                Return CType(Me("fukusyoCbV"),Boolean)
            End Get
            Set
                Me("fukusyoCbV") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property fukusyoExpectLowV() As Double
            Get
                Return CType(Me("fukusyoExpectLowV"),Double)
            End Get
            Set
                Me("fukusyoExpectLowV") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property fukusyoExpectHighV() As Double
            Get
                Return CType(Me("fukusyoExpectHighV"),Double)
            End Get
            Set
                Me("fukusyoExpectHighV") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property fukusyoOddsLowV() As Double
            Get
                Return CType(Me("fukusyoOddsLowV"),Double)
            End Get
            Set
                Me("fukusyoOddsLowV") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property fukusyoOddsHighV() As Double
            Get
                Return CType(Me("fukusyoOddsHighV"),Double)
            End Get
            Set
                Me("fukusyoOddsHighV") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property fukusyoParseV() As Double
            Get
                Return CType(Me("fukusyoParseV"),Double)
            End Get
            Set
                Me("fukusyoParseV") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property wakurenCbV() As Boolean
            Get
                Return CType(Me("wakurenCbV"),Boolean)
            End Get
            Set
                Me("wakurenCbV") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property wakurenExpectLowV() As Double
            Get
                Return CType(Me("wakurenExpectLowV"),Double)
            End Get
            Set
                Me("wakurenExpectLowV") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property wakurenExpectHighV() As Double
            Get
                Return CType(Me("wakurenExpectHighV"),Double)
            End Get
            Set
                Me("wakurenExpectHighV") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property wakurenOddsLowV() As Double
            Get
                Return CType(Me("wakurenOddsLowV"),Double)
            End Get
            Set
                Me("wakurenOddsLowV") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property wakurenOddsHighV() As Double
            Get
                Return CType(Me("wakurenOddsHighV"),Double)
            End Get
            Set
                Me("wakurenOddsHighV") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property wakurenParseV() As Double
            Get
                Return CType(Me("wakurenParseV"),Double)
            End Get
            Set
                Me("wakurenParseV") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property umarenCbV() As Boolean
            Get
                Return CType(Me("umarenCbV"),Boolean)
            End Get
            Set
                Me("umarenCbV") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property umarenExpectLowV() As Double
            Get
                Return CType(Me("umarenExpectLowV"),Double)
            End Get
            Set
                Me("umarenExpectLowV") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property umarenExpectHighV() As Double
            Get
                Return CType(Me("umarenExpectHighV"),Double)
            End Get
            Set
                Me("umarenExpectHighV") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property umarenOddsLowV() As Double
            Get
                Return CType(Me("umarenOddsLowV"),Double)
            End Get
            Set
                Me("umarenOddsLowV") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property umarenOddsHighV() As Double
            Get
                Return CType(Me("umarenOddsHighV"),Double)
            End Get
            Set
                Me("umarenOddsHighV") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property umarenParseV() As Double
            Get
                Return CType(Me("umarenParseV"),Double)
            End Get
            Set
                Me("umarenParseV") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property wideCbV() As Boolean
            Get
                Return CType(Me("wideCbV"),Boolean)
            End Get
            Set
                Me("wideCbV") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property wideExpectLowV() As Double
            Get
                Return CType(Me("wideExpectLowV"),Double)
            End Get
            Set
                Me("wideExpectLowV") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property wideExpectHighV() As Double
            Get
                Return CType(Me("wideExpectHighV"),Double)
            End Get
            Set
                Me("wideExpectHighV") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property wideOddsLowV() As Double
            Get
                Return CType(Me("wideOddsLowV"),Double)
            End Get
            Set
                Me("wideOddsLowV") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property wideOddsHighV() As Double
            Get
                Return CType(Me("wideOddsHighV"),Double)
            End Get
            Set
                Me("wideOddsHighV") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property wideParseV() As Double
            Get
                Return CType(Me("wideParseV"),Double)
            End Get
            Set
                Me("wideParseV") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property umatanCbV() As Boolean
            Get
                Return CType(Me("umatanCbV"),Boolean)
            End Get
            Set
                Me("umatanCbV") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property umatanExpectLowV() As Double
            Get
                Return CType(Me("umatanExpectLowV"),Double)
            End Get
            Set
                Me("umatanExpectLowV") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property umatanExpectHighV() As Double
            Get
                Return CType(Me("umatanExpectHighV"),Double)
            End Get
            Set
                Me("umatanExpectHighV") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property umatanOddsLowV() As Double
            Get
                Return CType(Me("umatanOddsLowV"),Double)
            End Get
            Set
                Me("umatanOddsLowV") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property umatanOddsHighV() As Double
            Get
                Return CType(Me("umatanOddsHighV"),Double)
            End Get
            Set
                Me("umatanOddsHighV") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property umatanParseV() As Double
            Get
                Return CType(Me("umatanParseV"),Double)
            End Get
            Set
                Me("umatanParseV") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property sanrenpukuCbV() As Boolean
            Get
                Return CType(Me("sanrenpukuCbV"),Boolean)
            End Get
            Set
                Me("sanrenpukuCbV") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property sanrenpukuExpectLowV() As Double
            Get
                Return CType(Me("sanrenpukuExpectLowV"),Double)
            End Get
            Set
                Me("sanrenpukuExpectLowV") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property sanrenpukuExpectHighV() As Double
            Get
                Return CType(Me("sanrenpukuExpectHighV"),Double)
            End Get
            Set
                Me("sanrenpukuExpectHighV") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property sanrenpukuOddsLowV() As Double
            Get
                Return CType(Me("sanrenpukuOddsLowV"),Double)
            End Get
            Set
                Me("sanrenpukuOddsLowV") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property sanrenpukuOddsHighV() As Double
            Get
                Return CType(Me("sanrenpukuOddsHighV"),Double)
            End Get
            Set
                Me("sanrenpukuOddsHighV") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property sanrenpukuParseV() As Double
            Get
                Return CType(Me("sanrenpukuParseV"),Double)
            End Get
            Set
                Me("sanrenpukuParseV") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property sanrentanCbV() As Boolean
            Get
                Return CType(Me("sanrentanCbV"),Boolean)
            End Get
            Set
                Me("sanrentanCbV") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property sanrentanExpectLowV() As Double
            Get
                Return CType(Me("sanrentanExpectLowV"),Double)
            End Get
            Set
                Me("sanrentanExpectLowV") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property sanrentanExpectHighV() As Double
            Get
                Return CType(Me("sanrentanExpectHighV"),Double)
            End Get
            Set
                Me("sanrentanExpectHighV") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property sanrentanOddsLowV() As Double
            Get
                Return CType(Me("sanrentanOddsLowV"),Double)
            End Get
            Set
                Me("sanrentanOddsLowV") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property sanrentanOddsHighV() As Double
            Get
                Return CType(Me("sanrentanOddsHighV"),Double)
            End Get
            Set
                Me("sanrentanOddsHighV") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property sanrentanParseV() As Double
            Get
                Return CType(Me("sanrentanParseV"),Double)
            End Get
            Set
                Me("sanrentanParseV") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property postHp() As Boolean
            Get
                Return CType(Me("postHp"),Boolean)
            End Get
            Set
                Me("postHp") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property postX() As Boolean
            Get
                Return CType(Me("postX"),Boolean)
            End Get
            Set
                Me("postX") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property postBks() As Boolean
            Get
                Return CType(Me("postBks"),Boolean)
            End Get
            Set
                Me("postBks") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property postEr() As Boolean
            Get
                Return CType(Me("postEr"),Boolean)
            End Get
            Set
                Me("postEr") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property postBuy() As Boolean
            Get
                Return CType(Me("postBuy"),Boolean)
            End Get
            Set
                Me("postBuy") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property postHit() As Boolean
            Get
                Return CType(Me("postHit"),Boolean)
            End Get
            Set
                Me("postHit") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property postBksLine() As Boolean
            Get
                Return CType(Me("postBksLine"),Boolean)
            End Get
            Set
                Me("postBksLine") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property bTansyo() As Boolean
            Get
                Return CType(Me("bTansyo"),Boolean)
            End Get
            Set
                Me("bTansyo") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property bTansyoExpectV() As Double
            Get
                Return CType(Me("bTansyoExpectV"),Double)
            End Get
            Set
                Me("bTansyoExpectV") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property bFukusyo() As Boolean
            Get
                Return CType(Me("bFukusyo"),Boolean)
            End Get
            Set
                Me("bFukusyo") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property bFukusyoExpectV() As Double
            Get
                Return CType(Me("bFukusyoExpectV"),Double)
            End Get
            Set
                Me("bFukusyoExpectV") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property bWakuren() As Boolean
            Get
                Return CType(Me("bWakuren"),Boolean)
            End Get
            Set
                Me("bWakuren") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property bWakurenExpectV() As Double
            Get
                Return CType(Me("bWakurenExpectV"),Double)
            End Get
            Set
                Me("bWakurenExpectV") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property bUmaren() As Boolean
            Get
                Return CType(Me("bUmaren"),Boolean)
            End Get
            Set
                Me("bUmaren") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property bUmarenExpectV() As Double
            Get
                Return CType(Me("bUmarenExpectV"),Double)
            End Get
            Set
                Me("bUmarenExpectV") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property bWide() As Boolean
            Get
                Return CType(Me("bWide"),Boolean)
            End Get
            Set
                Me("bWide") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property bWideExpectV() As Double
            Get
                Return CType(Me("bWideExpectV"),Double)
            End Get
            Set
                Me("bWideExpectV") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property bUmatan() As Boolean
            Get
                Return CType(Me("bUmatan"),Boolean)
            End Get
            Set
                Me("bUmatan") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property bUmatanExpectV() As Double
            Get
                Return CType(Me("bUmatanExpectV"),Double)
            End Get
            Set
                Me("bUmatanExpectV") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property bSanrenpuku() As Boolean
            Get
                Return CType(Me("bSanrenpuku"),Boolean)
            End Get
            Set
                Me("bSanrenpuku") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property bSanrenpukuExpectV() As Double
            Get
                Return CType(Me("bSanrenpukuExpectV"),Double)
            End Get
            Set
                Me("bSanrenpukuExpectV") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property bSanrentan() As Boolean
            Get
                Return CType(Me("bSanrentan"),Boolean)
            End Get
            Set
                Me("bSanrentan") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property bSanrentanExpectV() As Double
            Get
                Return CType(Me("bSanrentanExpectV"),Double)
            End Get
            Set
                Me("bSanrentanExpectV") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property bTohyoCountV() As Integer
            Get
                Return CType(Me("bTohyoCountV"),Integer)
            End Get
            Set
                Me("bTohyoCountV") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property pyMinV() As Integer
            Get
                Return CType(Me("pyMinV"),Integer)
            End Get
            Set
                Me("pyMinV") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property pySecV() As Integer
            Get
                Return CType(Me("pySecV"),Integer)
            End Get
            Set
                Me("pySecV") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property tohyoMinV() As Integer
            Get
                Return CType(Me("tohyoMinV"),Integer)
            End Get
            Set
                Me("tohyoMinV") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property tohyoSecV() As Integer
            Get
                Return CType(Me("tohyoSecV"),Integer)
            End Get
            Set
                Me("tohyoSecV") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property postHpMinV() As Integer
            Get
                Return CType(Me("postHpMinV"),Integer)
            End Get
            Set
                Me("postHpMinV") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property postHpSecV() As Integer
            Get
                Return CType(Me("postHpSecV"),Integer)
            End Get
            Set
                Me("postHpSecV") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property postBksMinV() As Integer
            Get
                Return CType(Me("postBksMinV"),Integer)
            End Get
            Set
                Me("postBksMinV") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property postBksSecV() As Integer
            Get
                Return CType(Me("postBksSecV"),Integer)
            End Get
            Set
                Me("postBksSecV") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property inetId() As String
            Get
                Return CType(Me("inetId"),String)
            End Get
            Set
                Me("inetId") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property kanyusyaNum() As String
            Get
                Return CType(Me("kanyusyaNum"),String)
            End Get
            Set
                Me("kanyusyaNum") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property secretNum() As String
            Get
                Return CType(Me("secretNum"),String)
            End Get
            Set
                Me("secretNum") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property pars() As String
            Get
                Return CType(Me("pars"),String)
            End Get
            Set
                Me("pars") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property inMoney() As Long
            Get
                Return CType(Me("inMoney"),Long)
            End Get
            Set
                Me("inMoney") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property autoInMoney() As Long
            Get
                Return CType(Me("autoInMoney"),Long)
            End Get
            Set
                Me("autoInMoney") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property autoNyukin() As Boolean
            Get
                Return CType(Me("autoNyukin"),Boolean)
            End Get
            Set
                Me("autoNyukin") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property logTxt() As String
            Get
                Return CType(Me("logTxt"),String)
            End Get
            Set
                Me("logTxt") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property tohyoMode() As Boolean
            Get
                Return CType(Me("tohyoMode"),Boolean)
            End Get
            Set
                Me("tohyoMode") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property zandaka() As Long
            Get
                Return CType(Me("zandaka"),Long)
            End Get
            Set
                Me("zandaka") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property localHost() As String
            Get
                Return CType(Me("localHost"),String)
            End Get
            Set
                Me("localHost") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property localUser() As String
            Get
                Return CType(Me("localUser"),String)
            End Get
            Set
                Me("localUser") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property localPw() As String
            Get
                Return CType(Me("localPw"),String)
            End Get
            Set
                Me("localPw") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property localDb() As String
            Get
                Return CType(Me("localDb"),String)
            End Get
            Set
                Me("localDb") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property awsHost() As String
            Get
                Return CType(Me("awsHost"),String)
            End Get
            Set
                Me("awsHost") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property awsPort() As String
            Get
                Return CType(Me("awsPort"),String)
            End Get
            Set
                Me("awsPort") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property awsUser() As String
            Get
                Return CType(Me("awsUser"),String)
            End Get
            Set
                Me("awsUser") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property awsPw() As String
            Get
                Return CType(Me("awsPw"),String)
            End Get
            Set
                Me("awsPw") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property awsDb() As String
            Get
                Return CType(Me("awsDb"),String)
            End Get
            Set
                Me("awsDb") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property LineToken() As String
            Get
                Return CType(Me("LineToken"),String)
            End Get
            Set
                Me("LineToken") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property HpUrl() As String
            Get
                Return CType(Me("HpUrl"),String)
            End Get
            Set
                Me("HpUrl") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property BookersToken() As String
            Get
                Return CType(Me("BookersToken"),String)
            End Get
            Set
                Me("BookersToken") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property xUserId() As String
            Get
                Return CType(Me("xUserId"),String)
            End Get
            Set
                Me("xUserId") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property xApiKey() As String
            Get
                Return CType(Me("xApiKey"),String)
            End Get
            Set
                Me("xApiKey") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property xApiKeyS() As String
            Get
                Return CType(Me("xApiKeyS"),String)
            End Get
            Set
                Me("xApiKeyS") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property xAccessTokenS() As String
            Get
                Return CType(Me("xAccessTokenS"),String)
            End Get
            Set
                Me("xAccessTokenS") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property xBearerToken() As String
            Get
                Return CType(Me("xBearerToken"),String)
            End Get
            Set
                Me("xBearerToken") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property xAccessToken() As String
            Get
                Return CType(Me("xAccessToken"),String)
            End Get
            Set
                Me("xAccessToken") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property tempDataTxt() As String
            Get
                Return CType(Me("tempDataTxt"),String)
            End Get
            Set
                Me("tempDataTxt") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property allDataTxt() As String
            Get
                Return CType(Me("allDataTxt"),String)
            End Get
            Set
                Me("allDataTxt") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property kaisai1() As String
            Get
                Return CType(Me("kaisai1"),String)
            End Get
            Set
                Me("kaisai1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property kaisai2() As String
            Get
                Return CType(Me("kaisai2"),String)
            End Get
            Set
                Me("kaisai2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property kaisai3() As String
            Get
                Return CType(Me("kaisai3"),String)
            End Get
            Set
                Me("kaisai3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property kaisai1Day() As String
            Get
                Return CType(Me("kaisai1Day"),String)
            End Get
            Set
                Me("kaisai1Day") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property kaisai2Day() As String
            Get
                Return CType(Me("kaisai2Day"),String)
            End Get
            Set
                Me("kaisai2Day") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property kaisai3Day() As String
            Get
                Return CType(Me("kaisai3Day"),String)
            End Get
            Set
                Me("kaisai3Day") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property postHpWinPercent() As Boolean
            Get
                Return CType(Me("postHpWinPercent"),Boolean)
            End Get
            Set
                Me("postHpWinPercent") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property setRaceNum() As Integer
            Get
                Return CType(Me("setRaceNum"),Integer)
            End Get
            Set
                Me("setRaceNum") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property minPercent() As Integer
            Get
                Return CType(Me("minPercent"),Integer)
            End Get
            Set
                Me("minPercent") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.中央競馬システム.My.MySettings
            Get
                Return Global.中央競馬システム.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
